options: &options
  adapter: postgresql
  encoding: utf8
  pool: 5
  username:
  password:
  template: template0 # Required for UTF8 encoding

development:
  <<: *options
  host: localhost
  database: clahub_development

test: &test
  <<: *options
  host: localhost
  database: clahub_test

production: &test
  <<: *options

